---

- block:
    - name: define | Build all LVS real servers list
      set_fact:
        lvs_realservers: >-
          {{ lvs_realservers
              + hostvars[item]['lvs_node_groups'] | default([])
                  | map('combine', {'host' : item})
                  | list
          }}
      delegate_to: "{{ item }}"
      loop: "{{ groups['lvs'] }}"

    - name: define | Build all LVS directors list
      set_fact:
        lvs_directors: >-
          {{ lvs_directors
              + hostvars[item]['lvs_director_groups'] | default([])
                  | map('combine', {'host' : item})
                  | list
          }}
      delegate_to: "{{ item }}"
      loop: "{{ groups['lvs'] }}"

    - name: define | Show all LVS real servers
      debug:
        var: lvs_realservers
    - name: define | Show all LVS directors
      debug:
        var: lvs_directors

  run_once: true

- block:
    - name: define | Group both LVS directors and real servers
      group_by:
        key: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_realservers + lvs_directors }}"

    - name: define | Group LVS real servers
      group_by:
        key: "lvs_{{ item.name }}_rs"
        parents: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_realservers }}"

    - name: define | Group LVS directors
      group_by:
        key: "lvs_{{ item.name }}_ds"
        parents: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_directors }}"

    - name: define | Show host groups
      debug:
        var: group_names

- block:
    - name: define | Show all groups
      debug:
        var: groups

    - name: define | Prepare groups yaml format
      set_fact:
        groups_yaml: >-
          {{ groups_yaml | combine(
                      { item.key :
                          { 'hosts' : dict(item.value | zip_longest([], fillvalue={})) }
                      }
                    )
          }}
      when: item.key.startswith('lvs')
      loop: "{{ groups | dict2items }}"

    - name: define | Save LVS groups
      copy:
        content: "{{ groups_yaml | to_yaml }}"
        dest: "{{ lvs_group_file }}"
      delegate_to: 'localhost'

  run_once: true

