---

- block:
    - name: define | Build all LVS real servers list
      set_fact:
        lvs_realservers: >-
          {{ lvs_realservers
              + hostvars[item]['lvs_node_groups'] | default([])
                  | map('combine', {'host' : item})
                  | list
          }}
      delegate_to: "{{ item }}"
      loop: "{{ groups['lvs'] }}"

    - name: define | Build all LVS directors list
      set_fact:
        lvs_directors: >-
          {{ lvs_directors
              + hostvars[item]['lvs_director_groups'] | default([])
                  | map('combine', {'host' : item})
                  | list
          }}
      delegate_to: "{{ item }}"
      loop: "{{ groups['lvs'] }}"

    - name: define | Show all LVS real servers
      debug:
        var: lvs_realservers
    - name: define | Show all LVS directors
      debug:
        var: lvs_directors

  run_once: true

- block:
    - name: define | Group both LVS directors and real servers
      group_by:
        key: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_realservers + lvs_directors }}"

    - name: define | Group LVS real servers
      group_by:
        key: "lvs_{{ item.name }}_rs"
        parents: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_realservers }}"

    - name: define | Group LVS directors
      group_by:
        key: "lvs_{{ item.name }}_ds"
        parents: "lvs_{{ item.name }}"
      when: item.host == inventory_hostname
      loop: "{{ lvs_directors }}"

    - name: Print groups
      debug:
        var: group_names

