---

- block:

    - name: Build full lvs director config
      set_fact:
        lvs_director: >-
          {{ lvs_director + [ item | combine(
                { 'real_addresses': lvs_realservers
                    | selectattr('name', 'equalto', item.name)
                    | map(attribute='address') | ipaddr('address')
                    | list
                , 'virtual_addresses': item.virtual_addresses
                    | map(attribute='address') | ipaddr('address')
                    | list
                })
              ]
          }}
      loop: "{{ lvs_director_groups }}"

    - name: Show full lvs director config
      debug:
        msg: "{{ lvs_director }}"

  tags:
    - debug

- block:

    - name: Generate keepalived config
      template:
        src: 'keepalived.conf'
        dest: '/etc/keepalived/keepalived.conf'
        backup: yes
        owner: root
      notify:
        - restart keepalived

