---

- block:

    - name: director | Build full lvs director config
      set_fact:
        lvs_director_conf: >-
          {{ lvs_director_conf + [ item | combine(
                { 'real_addresses': lvs_realservers
                    | selectattr('name', 'equalto', item.name)
                    | map(attribute='address') | ipaddr('address')
                    | list
                , 'virtual_addresses': item.virtual_addresses
                    | map(attribute='address') | ipaddr('address')
                    | list
                })
              ]
          }}
      loop: "{{ lvs_director_groups }}"

    - name: director | Build full VRRP config
      set_fact:
        vrrp_conf: >-
          {{ vrrp_conf + [
                { 'unicast_src_ip': unicast_src_ip
                , 'unicast_peer': vrrp_instances
                    | selectattr('instance', 'equalto', item.instance)
                    | map(attribute='unicast_src_ip') | map(attribute='address') | ipaddr('address')
                    | reject('equalto', unicast_src_addr)
                    | list
                } | combine(item)
              ]
          }}
      vars:
        unicast_src_addr: "{{ item.unicast_src_ip.address | default(ansible_host) }}"
      loop: "{{ vrrp }}"

    - name: director | Show full LVS director config
      debug:
        var: lvs_director_conf
    - name: director | Show full VRRP config
      debug:
        var: vrrp_conf

  tags:
    - always

- block:

    - name: director | Generate keepalived config
      template:
        src: 'keepalived.conf'
        dest: '/etc/keepalived/keepalived.conf'
        backup: yes
        owner: root
      notify:
        - restart keepalived

